Repository pokemon-tabletop-reunited/ptr1e, pull requests merged in 2023-04, with the labels that each got.

#351 Custom Species Editor, editable capability values
  module/api/front-end/components/cse-capabilities.js
  module/api/front-end/cseStore.js
  module/forms/cse-form.js
  templates/forms/cse.hbs
Labels: bug

#349 +/- values into hp/exp fields
  module/ptu.js
  templates/actor/character-sheet-gen8.hbs
  templates/actor/pokemon-sheet-gen8.hbs
Labels: enhancement, Trainer Sheet, Pokémon Sheet

#354 implement move speed icons
  css/main.css
  css/ptu.less
  module/ptu.js
  module/settings.js
Labels: enhancement, P2

#352 evolution glow
  module/api/front-end/components/monImageComponent.js
  module/api/front-end/levelupStore.js
  module/forms/level-up-form.js
  module/settings.js
Labels: enhancement, P3

#353 apply effects for status moves
  module/combat/damage-calc-tools.js
  templates/chat/automation/applied-effect.hbs
  templates/chat/moves/damage-application.hbs
Labels: enhancement, P1

#337 Addressing Issue #319 and working towards #336
  module/combat/effects/pokeball_effects.js
  module/utils/item-piles-compatibility-handler.js
Labels: help wanted, question, Stale
